### ISSUE TITLE
TOML parser exception in IDEA 15

### ISSUE THREAD

**Issue by e-oz** [alexeykudinkin/intellij-rust#144]
OS X 10.11.1
IDEA 15 143.382

```
Language Language: TOML doesn't participate in view provider SingleRootFileViewProvider{myVirtualFile=file:///path/Cargo.toml, content=VirtualFileContent{size=502}}: [Language: TOML]
java.lang.AssertionError: Language Language: TOML doesn't participate in view provider SingleRootFileViewProvider{myVirtualFile=file:///path/Cargo.toml, content=VirtualFileContent{size=502}}: [Language: TOML]
	at com.intellij.extapi.psi.PsiFileBase.a(PsiFileBase.java:58)
	at com.intellij.extapi.psi.PsiFileBase.<init>(PsiFileBase.java:40)
	at org.toml.lang.core.psi.TomlFile.<init>(TomlFile.kt:9)
	at org.toml.lang.core.parser.TomlParserDefinition.createFile(TomlParserDefinition.kt:24)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:412)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:353)
	at com.intellij.psi.SingleRootFileViewProvider.a(SingleRootFileViewProvider.java:331)
	at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:176)
	at com.intellij.psi.SingleRootFileViewProvider.getPsi(SingleRootFileViewProvider.java:160)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:410)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:184)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.processChildren(PsiDirectoryImpl.java:197)
	at com.intellij.ide.projectView.impl.nodes.ProjectViewDirectoryHelper.a(ProjectViewDirectoryHelper.java:182)
	at com.intellij.ide.projectView.impl.nodes.ProjectViewDirectoryHelper.getDirectoryChildren(ProjectViewDirectoryHelper.java:132)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.getChildrenImpl(PsiDirectoryNode.java:163)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.getChildren(AbstractPsiBasedNode.java:83)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:47)
	at com.intellij.ide.util.treeView.AbstractTreeUi$32.perform(AbstractTreeUi.java:1624)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1621)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4700(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1546)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1533)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1259)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$3100(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$26$1.perform(AbstractTreeUi.java:1182)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$26.perform(AbstractTreeUi.java:1179)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1174)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1080)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
	at com.intellij.ide.util.treeView.AbstractTreeUi$13.perform(AbstractTreeUi.java:510)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doExpandNodeChildren(AbstractTreeUi.java:506)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.expandNodeChildren(AbstractTreeBuilder.java:355)
	at com.intellij.ide.projectView.BaseProjectTreeBuilder.expandNodeChildren(BaseProjectTreeBuilder.java:118)
	at com.intellij.ide.util.treeView.AbstractTreeUi$MyExpansionListener.treeExpanded(AbstractTreeUi.java:4817)
	at javax.swing.JTree.fireTreeExpanded(JTree.java:2774)
	at javax.swing.JTree.setExpandedState(JTree.java:3625)
	at javax.swing.JTree.expandPath(JTree.java:2211)
	at javax.swing.plaf.basic.BasicTreeUI.toggleExpandState(BasicTreeUI.java:2286)
	at javax.swing.plaf.basic.BasicTreeUI.handleExpandControlClick(BasicTreeUI.java:2273)
	at javax.swing.plaf.basic.BasicTreeUI.checkForClickInExpandControl(BasicTreeUI.java:2231)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3600)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressedDND(BasicTreeUI.java:3586)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3545)
	at com.intellij.util.ui.MouseEventAdapter.mousePressed(MouseEventAdapter.java:41)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.a(IdeGlassPaneImpl.java:427)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.dispatch(IdeGlassPaneImpl.java:199)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:603)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by matklad** [comment]
Could you provide some more details about how this happened? I am unable to reproduce the issue at the moment.

**Comment by e-oz** [comment]
Installed plugin, opened IDE.

**Comment by matklad** [comment]
Could you try the plugin from this branch: https://github.com/alexeykudinkin/intellij-rust/tree/eager-TOML ? It should fix the issue, but I can't check it.

**Comment by e-oz** [comment]
yes, now all is fine, no exceptions. Thank you!

**Comment by matklad** [comment]
Thanks to you for revealing this lazy loading bug :)
